# Generated by Django 5.0.6 on 2026-10-09 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear_taller', 'Crear taller'), ('editar_taller', 'Editar taller'), ('baja_taller', 'Baja taller'), ('aprobar_docente', 'Aprobar docente'), ('rechazar_docente', 'Rechazar docente'), ('registrar_pago', 'Registrar pago'), ('anular_pago', 'Anular pago'), ('suspender_clase', 'Suspender clase'), ('crear_novedad', 'Crear novedad')], max_length=30, verbose_name='Accion')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
