# Generated by Django 5.0.6 on 2026-10-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_anio', models.DateField(verbose_name='Mes y anio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (ARS)')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('parcial', 'Pago parcial'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='inscripciones.inscripcion', verbose_name='Inscripcion')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-mes_anio'],
                'unique_together': {('inscripcion', 'mes_anio')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (ARS)')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Debito')], max_length=20, verbose_name='Metodo de pago')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('motivo_anulacion', models.TextField(blank=True, verbose_name='Motivo de anulacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pagos.cuota', verbose_name='Cuota')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
