# Generated by Django 5.0.6 on 2026-10-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tema', models.CharField(blank=True, max_length=200, verbose_name='Tema')),
                ('suspendida', models.BooleanField(default=False, verbose_name='Suspendida')),
                ('motivo_suspension', models.TextField(blank=True, verbose_name='Motivo de suspension')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='talleres.taller', verbose_name='Taller')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['-fecha'],
                'unique_together': {('taller', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificado', 'Justificado')], default='presente', max_length=20, verbose_name='Estado')),
                ('justificacion', models.TextField(blank=True, verbose_name='Justificacion')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='inscripciones.inscripcion', verbose_name='Inscripcion')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.clase', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-clase__fecha'],
                'unique_together': {('clase', 'inscripcion')},
            },
        ),
    ]
